import { Controller, Get, Param, Query, Redirect, UseGuards } from '@nestjs/common';
import { GoogledriveService } from './googledrive.service';
import { AuthGuard } from '../auth/auth.guard';
import { RolesGuard } from '../auth/roles.guard';
import { Roles } from '../auth/roles.decorator';



@Controller('googledrive')
export class GoogledriveController {
    constructor(
        private readonly googledriveService : GoogledriveService
    ){}

    @Get()
    // the user need to be logged to use this endpoint and ensure that the tokens will be generated by a SuperAdmin user
    @UseGuards(AuthGuard, RolesGuard)
    @Roles('SuperAdmin')
    @Redirect()
    async redirectToGoogle() {
        const url = await this.googledriveService.generateAuthUrl();
        return {url: url};
    }

    @Get('callback')
    async handleGoogleCallback(@Query('code') code: string) {
        const tokens = await this.googledriveService.getTokens(code);
        //return tokens;
        return { 
            status: 200,
            message: 'Authentication successful! Tokens received.'
        };
    }

}


