service: nest-api-local

org: null
app: null
dashboard: false

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: dev
  memorySize: 1024
  timeout: 600
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: 'arn:aws:lambda:us-east-1:*:function:medvirtual-ml-service-*'

layers:
  poppler:
    path: layers/poppler
    name: poppler-utils
    compatibleRuntimes:
      - nodejs16.x
      - nodejs18.x
      - nodejs20.x

functions:
  api:
    handler: dist/index.handler
    timeout: 600
    memorySize: 1024
    layers:
      - { Ref: PopplerLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

package:
  individually: true
  excludeDevDependencies: true
