#File responsible for simulate a lambda locally
service: nest-api-local

org: null
app: null
dashboard: false

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 600

functions:
  api:
    handler: dist/index.handler
    timeout: 600
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin:
              - https://app.medvirtual.ai
              - https://staging.medvirtual.ai
              - http://localhost:3000
              - http://localhost:3001
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
            allowCredentials: true
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - HEAD
              - OPTIONS

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
    
package:
  individually: true
  excludeDevDependencies: true
