export const latinAmericaCountries = [
  'Brazil',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Uruguay',
  'Paraguay',
  'Bolivia',
  'Ecuador',
  'Venezuela',
  'Mexico',
  'Costa Rica',
  'Panama',
  'Guatemala',
  'Honduras',
  'El Salvador',
  'Nicaragua',
  'Cuba',
  'Dominican Republic',
  'Puerto Rico',
];
