name: Deploy at AWS Lambda

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: 🧾 Code Checkout
        uses: actions/checkout@v4

      - name: 📦 Install dependencies
        run: npm ci
      
      - name: 📦 remove binaries from macOs
        run: rm -rf node_modules/.prisma

      - name: Update binaryTargets for production (Linux)
        run: sed -i 's/binaryTargets = \["native"\]/binaryTargets = \["rhel-openssl-1.0.x"\]/' prisma/schema.prisma

      - name: 🧱 Prisma by docker
        run: docker run --rm -v $(pwd):/app -w /app -e PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1 node:18 npx prisma generate

      - name: 🔨 Build with webpack
        #run: npm run build:esbuild
        run: npx webpack --config webpack.config.js

          

      - name: 📁 Build lambda-package
        run: |
          mkdir lambda-package
          cp -r dist/* lambda-package/
          cp -r prisma/schema.prisma lambda-package/prisma/
          cp package.prod.json lambda-package/package.json
          if [ -f .env ]; then cp .env lambda-package/; else echo "⚠️  Arquivo .env não encontrado, ignorando..."; fi

      - name: 📦 Install just production dependencies
        working-directory: lambda-package
        run: npm install --omit=dev
      
      - name: 🧹 Remove arquivos .map
        run: find lambda-package -name "*.map" -type f -delete

      - name: 📦 Copy prisma binaries
        run: |
          mkdir -p lambda-package/node_modules/.prisma
          cp -r node_modules/.prisma/* lambda-package/node_modules/.prisma/

      - name: 📦 Build ZIP files
        working-directory: lambda-package
        run: zip -r ../lambda.zip . > /dev/null

      - name: 🚀 Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🚀 Deploy at AWS Lambda
        run: |
            aws lambda update-function-code \
              --function-name $LAMBDA_FUNCTION_NAME \
              --zip-file fileb://lambda.zip \
              --no-cli-pager \
              --output text

      - name: 🧹 Clean temp files
        run: rm -rf lambda-package lambda.zip
